# permissions for end users to edit autoheals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoheal-editor-role
rules:
- apiGroups:
  - autoheal.redhat.com
  resources:
  - autoheals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoheal.redhat.com
  resources:
  - autoheals/status
  verbs:
  - get
