# permissions for end users to view autoheals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoheal-viewer-role
rules:
- apiGroups:
  - autoheal.redhat.com
  resources:
  - autoheals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoheal.redhat.com
  resources:
  - autoheals/status
  verbs:
  - get
